### ISSUE TITLE
Deterministic validation of closure property in building.

### ISSUE THREAD

**Issue by xgbuils** [fibo/algebra-group#5]
Hi @fibo,

I don't have much time this weekend but I want to let you know that I'm working in new repository called [algebra-set](https://github.com/xgbuils/algebra-set).

I had the idea when I see that group in this library is defined using `identity`, `contains`, `equality`, `compositionLaw` and `inversion`. However in maths is defined with set and operation. `contains` and `equality` are attributes of set, and `identity`, `compositionLaw` and `inversion` are attributes of operation where `identity === compositionLaw(x, inversion(x))`.

Also I think that is possible to define operations like sum or multiplication over reals and associate to these operations the image based on the domain that applies. For example, given an interval (a, b] we know that the image of sum over (a, b] is (2_a, 2_b].

Then, it's possible to define a group in this way:

```
algebraGroup({
    set: '[-1, 0) U (0, 1]',
    op: operation.MUL
})
```

And check if this group is closed over certain predefined operations.

**Comment by fibo** [comment]
I did not studied cathegory theory, but, *identity* looks between *set* and *operation*. Actually is a set of cardinality 1, contained in the given set.

OT maybe you want to try my matrices of string excercise: https://www.npmjs.com/package/matrix-multiplication

**Comment by fibo** [comment]
`'[-1, 0) U (0, 1]'` cound be implemented as

```
// This is pseudo code
function contains1 (x) { return -1 =< x < 0 } 
function contains2 (x) { return 0 < x =< 1 }

function contains (x) { return contains(1) || contains(2) }
```

I mean that *union* looks like *or*, and *intersection* looks like *and*.

**Comment by xgbuils** [comment]
I did not express myself well, sorry.

(1, Infinity] and (0, Infinity] could be implemented thus:
```
function greater1 (x) { return x > 1}
function greater0 (x) { return x > 0}
```
But you can't know if greater1 is a subset of greater0 with this functions. I'm working to express set in another way that "contains function" because, thus, it's possible to know if set is subset of another set and validate the closure property, at least, of some groups.
